### ISSUE TITLE
Not working with CFG on

### ISSUE THREAD

**Issue by Dump-GUY** [hasherezade/process_overwriting#1]
Tested environment:
WIN 10 x64 21h1
WIN 7 x64

When I choose different target (of course 32bit payload to 32bit process) - everything is working.
Like specifying target path to non buildin windows binaries - example (process_overwriting.exe demo.bin "C:\Users\Inferno\Desktop\IAT_Patcher_x86\IAT_Patcher.exe")

When I try to inject to default calc.exe or specifying path to calc.exe or cmd.exe for example it does not work -> WerFault.
Output looks like everything is ok (DONE etc.) but goes to WerFault.
Tested binaries build from AppVeyor (both 32bit and 64bit release\debug).

After some testing it is caused by CFG (Optional Header -> DllCharacteristics -> GUARD_CF) - if disabled on binary -> working well.

**Comment by hasherezade** [comment]
This is true, I added it to the README as one of the limitations.
Thank you!
